# Generated by Django 4.1.1 on 2022-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pk першого зображення'),
        ),
    ]
