# Generated by Django 4.1.1 on 2022-09-12 16:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=users.models.path_and_rename, verbose_name='Зображення'),
        ),
    ]
