# Generated by Django 4.1.1 on 2022-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Тамбнейл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Зображення'),
        ),
    ]
