# Generated by Django 4.1 on 2022-09-04 11:08

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=posts.models.image_dir),
        ),
    ]
