# Generated by Django 4.1.1 on 2022-09-21 17:13

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0002_alter_image_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=posts.models.path_and_rename, verbose_name='Зображення'),
        ),
    ]
