# Generated by Django 4.1.1 on 2022-09-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_first_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_image',
        ),
        migrations.AddField(
            model_name='image',
            name='is_first',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_image', to='posts.post'),
        ),
    ]
