# Generated by Django 4.1.2 on 2022-10-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_tags_alter_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumbnail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_thumbnail',
        ),
    ]
