# Generated by Django 4.1.1 on 2022-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_first_image_new_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
