# Generated by Django 4.1.2 on 2022-10-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_image_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Тамбнейл'),
        ),
    ]
