# Generated by Django 4.1.2 on 2022-10-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_thumbnail',
        ),
    ]
