# Generated by Django 4.1.1 on 2022-09-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_first_image_new_post_first_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_image',
            new_name='content_type',
        ),
    ]
