# Generated by Django 4.1.1 on 2022-09-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_first_image_post_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_first',
        ),
    ]
