# Generated by Django 4.1.2 on 2022-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Тамбнейл'),
        ),
    ]
