# Generated by Django 4.1.1 on 2022-09-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_image_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_id',
        ),
    ]
