# Generated by Django 4.1.1 on 2022-09-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_content_type_remove_post_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fav_post', to='posts.image'),
        ),
    ]
