# Generated by Django 4.1.1 on 2022-09-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.image'),
        ),
    ]
