# Generated by Django 4.1.1 on 2022-09-05 19:07

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.path_and_rename, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_invisible',
            field=models.BooleanField(default=False, verbose_name="Сором'змива дупа"),
        ),
    ]
