# Generated by Django 4.1.1 on 2022-09-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
    ]
