# Generated by Django 4.1.1 on 2022-09-06 09:04

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.path_and_rename, verbose_name='Аватарка'),
        ),
    ]
