# Generated by Django 4.1.1 on 2022-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_invisible',
            field=models.BooleanField(default=False, verbose_name="Сором'змива дупа"),
        ),
    ]
