# Generated by Django 4.1 on 2022-08-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_invivible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_invivible',
        ),
    ]
