# Generated by Django 4.1 on 2022-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_invivible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invisible',
            field=models.BooleanField(default=False, verbose_name="Сором'змива дупа"),
        ),
    ]
