branch-defaults:
  dev:
    environment: Dg-app-env
    group_suffix: null
environment-defaults:
  db-env:
    branch: null
    repository: null
global:
  application_name: dg-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
